### ISSUE TITLE
Support for implicit XMI ids

### ISSUE THREAD

**Issue by massimotisi** [atlanmod/ATLGT#2]
Implicit XMI ids are not stable during synchronization. 

A possible solution could be assigning explicit ids to Elements as soon as they are loaded (before any transformation step).

**Comment by massimotisi** [comment]
But if the model has explicitly assigned ids, we should not overwrite them.

**Comment by yvrng** [comment]
Identifiers are generated when loading, only if they are non-existent or malformed (XPath-like), by using the `EcoreUtil.generateUUID()` method. See the [javadoc](http://download.eclipse.org/modeling/emf/emf/javadoc/2.6.0/org/eclipse/emf/ecore/util/EcoreUtil.html#generateUUID()) for more information.
