### ISSUE TITLE
Catch the exception earlier in the forward/backward command invocation chains

### ISSUE THREAD

**Issue by sohidaka** [atlanmod/ATLGT#9]
When one of a command in the foward/backward transformation chains raises exception, suppressing the execution of the rest of the commands would reduce response time.

**Comment by yvrng** [comment]
It should be fixed. Can you confirm ?
We consider that an external command has failed if it returns `exitValue != 0`

**Comment by sohidaka** [comment]
Thanks for the perfect solution. I am going to close this issue.
